name: plasmidgpt_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - torch=2.0.1
  - transformers=4.37.2
  - pandas=2.2.0
  - scikit-learn
  - matplotlib
  - seaborn
  - biopython
  - numpy
  - pip
  - pip:
      - PreTrainedTokenizerFast
